const ONE_HOUR = 1000 * 60 * 60

const TWELVE_HOURS = ONE_HOUR * 12

export const BCRYPT_WORK_FACTOR = 10

export const EMAIL_VERIFICATION_TIMEOUT = TWELVE_HOURS

export const PASSWORD_RESET_TIMEOUT = ONE_HOUR

export const PASSWORD_RESET_BYTES = 40